#pragma once
constexpr auto CPPHTTPLIB_REDIRECT_MAX_COUNT = 20;
constexpr auto CPPHTTPLIB_READ_TIMEOUT_SECOND = 5;
constexpr auto CPPHTTPLIB_READ_TIMEOUT_USECOND = 0;
constexpr auto CPPHTTPLIB_WRITE_TIMEOUT_SECOND = 5;
constexpr auto CPPHTTPLIB_WRITE_TIMEOUT_USECOND = 0;
constexpr auto CPPHTTPLIB_KEEPALIVE_MAX_COUNT = 5;